# Generated by Django 3.1.4 on 2021-01-16 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentno', models.CharField(max_length=100)),
                ('patientname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(default='NA', max_length=200)),
                ('dateofbirth', models.DateField()),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=100)),
                ('appointmentdate', models.DateField(default=datetime.date.today)),
                ('appointmenttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='enduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='appointmentstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('comment', models.CharField(default='Yet to Review', max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser'),
        ),
    ]
