# Generated by Django 3.1.4 on 2021-01-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderamount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
                ('testchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.testchoice')),
            ],
        ),
    ]
