# Generated by Django 3.1.4 on 2021-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_orderamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='testchoice',
            name='orderamount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='orderamount',
        ),
    ]
