# Generated by Django 3.1.4 on 2021-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_testchoice_orderamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentno',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='orderamount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment', to_field='appointmentno')),
            ],
        ),
    ]
