# Generated by Django 3.1.4 on 2021-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210205_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
