# Generated by Django 3.1.4 on 2021-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appointment_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
