# Generated by Django 3.1.4 on 2021-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
