# Generated by Django 3.1.4 on 2021-01-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210121_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('orderid', models.CharField(max_length=100)),
                ('paymentid', models.CharField(max_length=100)),
                ('paymentstatus', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment', to_field='appointmentno')),
            ],
        ),
    ]
