# Generated by Django 3.1.4 on 2021-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210122_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='amountdue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='codstatus',
            field=models.BooleanField(default=False),
        ),
    ]
