# Generated by Django 3.1.4 on 2021-01-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210123_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
