# Generated by Django 3.1.4 on 2021-01-30 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20210121_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(default='Order Placed', max_length=500)),
                ('ordertimestamp', models.DateField(auto_now_add=True)),
                ('updatetimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment', to_field='appointmentno')),
            ],
        ),
    ]
