# Generated by Django 3.1.4 on 2021-02-05 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordertracking', '0004_auto_20210130_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackorder',
            name='updatetimestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
